using System;
using System.Collections.Generic;
using Shares.Domain.Entities;

namespace Shares.Domain
{
    public static class Constants
    {
        public static readonly List<string> CurrentPerformanceTickers =
        [
            "VTSMX",
            "^DJI",
            "%5EIXIC",
            "CSSPX.MI",
            "VUSD.L",
            "^BSESN",
            "^NSEI",
            "SPY5.L",
            "EXXT.DE",
            "XLKS.MI",
            "QQQ3.MI",
            "BRK-B",
            "4GLD.DE",
            "SGBS.MI",
            "XAD6.DE",
            "ASML",
            "NVDA",
            "GOOGL",
            "MSFT",
            "AAPL",
            "AVGO",
            "INTC",
            "AMD",
            "TSM",
            "MU",
            "QCOM",
            "LRCX",
            "NXPI",
            "TER",
            "ADBE",
            "META",
            "NFLX",
            "ISRG",
            "CRM",
            "AMZN",
            "NKE",
            "PYPL",
            "IBM",
            "ARM",
            "SNPS",
            "NVO",
            "LLY",
            "KOG.OL",
            "RHM.DE",
            "SDV1.F",
            "HO.PA",
            "TSLA",
            "ETSY",
            "PLTR",
            "DIS",
            "ABNB",
            "AMS.SW",
            "STNE",
            "FTK.DE",
            "KLAC",
            "MA",
            "AIR",
            "OXY",
            "ORCL",
            "AD.AS",
            "BABA",
            "SRG",
            "SAP",
            "SHEL",
            "BP",
            "UNH"
        ];

        internal static readonly List<string> StockAverageTickers =
        [
            "EXXT.DE",
            "XLKS.MI",
            "%5EIXIC",
            "ASML",
            "NVDA",
            "AMD",
            "PYPL",
            "GOOGL",
            "MSFT",
            "LRCX",
            "AAPL",
            "TER",
            "TSM",
            "ADBE",
            "ISRG",
            "META",
            "AVGO",
            "QCOM",
            "NKE",
            "NFLX",
            "CRM",
            "KLAC",
            "MU",
            "AMZN",
            "TSLA",
            "ETSY",
            "PLTR",
            "STNE",
            "DIS",
            "ABNB",
            "FTK.DE",
            "BRK-B",
            "VTSMX",
            "CSSPX.MI",
            "VUSD.L",
            "MA",
            "AIR",
            "OXY",
            "NXPI",
            "ORCL",
            "AD.AS",
            "BABA",
            "SRG",
            "SAP",
            "INTC",
            "SHEL",
            "BP",
            "AMS.SW",
            "SPY5.L",
            "4GLD.DE",
            "SGBS.MI",
            "^DJI",
            "^BSESN",
            "^NSEI",
            "IBM",
            "ARM",
            "QQQ3.MI",
            "XAD6.DE",
            "NVO",
            "LLY",
            "KOG.OL",
            "RHM.DE",
            "SDV1.F",
            "HO.PA",
            "UNH",
            "SNPS"
        ];
        
        public static readonly List<string> IgnoredFinancialMetricsTickers =
        [
            "VTSMX",
            "^DJI",
            "%5EIXIC",
            "CSSPX.MI",
            "VUSD.L",
            "^BSESN",
            "^NSEI",
            "SPY5.L",
            "EXXT.DE",
            "XLKS.MI",
            "QQQ3.MI",
            "4GLD.DE",
            "SGBS.MI",
            "XAD6.DE",
            "KOG.OL",
            "RHM.DE",
            "SDV1.F",
            "HO.PA",
            "AMS.SW",
            "STNE",
            "FTK.DE",
            "AD.AS",
            "SRG",
        ];

        internal static readonly List<PercentageInterval> PercentageIntervals =
        [
            new(3, 5),
            new(5, 7),
            new(7, 10),
            new(10, 15),
            new(15, 20),
            new(20, 30),
            new(30, 40),
            new(40, 100)
        ];

        internal static readonly List<YearInterval> YearIntervals =
        [
            new(new DateTime(2021, 01, 01), new DateTime(2025, 12, 31)),
            new(new DateTime(2016, 01, 01), new DateTime(2020, 12, 31)),
            new(new DateTime(2011, 01, 01), new DateTime(2015, 12, 31))
        ];

        internal static readonly List<PercentageIntervalForStopLoss> PercentageIntervalsForStopLoss =
        [
            new(7, 4),
            new(10, 6),
            new(15, 10),
            new(20, 14),
            new(25, 18),
            new(30, 22),
            new(40, 30)
        ];
    }
}
